require 'tsvim.config.options'
require 'tsvim.config.keymaps'
require 'tsvim.config.autocmds'

-- Plugin imports
local spec = require('tsvim.util.spec').spec
spec 'tsvim.plugins.bufferline'
spec 'tsvim.plugins.colors'
spec 'tsvim.plugins.typescript'
spec 'tsvim.plugins.conform'
spec 'tsvim.plugins.dashboard-vim'
spec 'tsvim.plugins.dressing'
spec 'tsvim.plugins.fortune'
spec 'tsvim.plugins.gitsigns'
spec 'tsvim.plugins.indent'
spec 'tsvim.plugins.lualine'
spec 'tsvim.plugins.neo-tree'
spec 'tsvim.plugins.neotest'
spec 'tsvim.plugins.noice'
spec 'tsvim.plugins.nvim-cmp'
spec 'tsvim.plugins.nvim-dap'
spec 'tsvim.plugins.nvim-lspconfig'
spec 'tsvim.plugins.nvim-notify'
spec 'tsvim.plugins.telescope'
spec 'tsvim.plugins.toggleterm'
spec 'tsvim.plugins.treesitter'
spec 'tsvim.plugins.trouble'
spec 'tsvim.plugins.vim-tmux-navigator'
spec 'tsvim.plugins.which-key'

require 'tsvim.config.lazy'
